---
- name: vm-test-creator
  hosts: localhost
  become: true
  tasks:
    - name: Creating vm on kubevirt cluster
      kubevirt_vm:
        api_key: "{{ kv_vm_api_token }}"
        state: running
        validate_certs: false
        name: "{{ kv_vm_name }}"
        host: "{{ kv_vm_host }}"
        namespace: "{{kv_vm_namespace}}"
        memory: 512Mi
        cpu_cores: 2
